services:
  db:
    container_name: hr-db
    image: postgres
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
